alias ls='ls --color=auto'
alias rg='rg -i'
alias grep='grep --color=auto'
alias update='sudo pacman -Syy'
alias upgrade='sudo pacman -Syu'
alias install='sudo pacman -S'
alias list='sudo pacman -Q'
alias l='ls'
alias ll='ls -l'
alias c='clear'
alias music='ncmpcpp'
